# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Danger
        uses: 417-72KI/danger-swiftlint@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
